config/routes.rb
Rails.application.routes.draw do
  root to: 'albums#index'
  resources :albums do
    resources :songs
    resources :artists
  end
  resources :artists do
    resources :genres
  end
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :album_artists
  has_many :artists, :through => :album_artists
  validates :name, presence: true
  validates_length_of :name, maximum: 100
  before_save(:titleize_album)
  scope :rock, -> { where(genre: "Rock")}
  
  private
    def titleize_album
      self.name = self.name.titleize
    end
end

app/models/album_artist.rb
class AlbumArtist < ApplicationRecord
  belongs_to :artist
  belongs_to :album
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :album_artists
  has_many :albums, :through => :album_artists
  has_many :artist_genres
  has_many :genres, :through => :artist_genres
end

app/models/artist_genre.rb
class ArtistGenre < ApplicationRecord
  belongs_to :artist
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :artist_genres
  has_many :artists, :through => :artist_genres
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
require 'pry'

class AlbumsController < ApplicationController

  def index
    @albums = Album.all
    render :index
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:notice] = "Album successfully added!"
      redirect_to albums_path
    else
      render :new
    end
  end

  # Other controller methods go here.

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @artist = artist.find(params[:artist_id])
    @album= Album.find(params[:id])
    @album.artists.new(@artist)
    @album.save
    if @album.update(album_params)
      redirect_to albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end

  private
  def album_params
    params.require(:album).permit(:name, :genre)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
require 'pry'
class ArtistsController < ApplicationController

  def index
    @album = Album.find(params[:album_id])
    @artists = Artist.all
    render :index
  end

  def new
    @album = Album.find(params[:album_id])
    @artist = @album.artists.new
    render :new
  end

  def create
    @album = Album.find(params[:album_id])
    @artist = @album.artists.new(artist_params)
    if @album.save(@artist)
      redirect_to album_path(@album)
    else
      render :new
    end
  end

def edit
  @album = Album.find(params[:album_id])
  @artist = Artist.find(params[:id])
  render :edit
end

def show
  @album = Album.find(params[:album_id])
  @artist = Artist.find(params[:id])
  render :show
end

def update
  @album = Album.find(params[:album_id])
  @artist = Artist.find(params[:id])
  if @artist.update(artist_params)
    redirect_to album_path(@album)
  else
    render :edit
  end
end

def destroy
  @album = Album.find(params[:album_id])
  @artist = Artist.find(params[:id])
  @artist.destroy
  redirect_to album_path(@album)
end

private
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/genres_controller.rb
require 'pry'
class GenresController < ApplicationController

  def index
    @artist = Artist.find(params[:artist_id])
    @genre = Genre.all
    render :index
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @genre = @artist.genres.new
    render :new
  end

  def create
    @album = Album.find(:album)
    @artist = Artist.find(params[:artist_id])
    @genre = @artist.genres.new(genre_params)
    if @artist.save(@genre)
      redirect_to album_path(@album)
    else
      render :new
    end
  end

def edit
  @artist = Artist.find(params[:artist_id])
  @genre = Genre.find(params[:id])
  render :edit
end

def show
  @artist = Artist.find(params[:artist_id])
  @genre = Genre.find(params[:id])
  render :show
end

def update
  @artist = Artist.find(params[:artist_id])
  @genre = Genre.find(params[:id])
  if @genre.update(genre_params)
    redirect_to album_path(@album)
  else
    render :edit
  end
end

def destroy
  @artist = Artist.find(params[:artist_id])
  @genre = Genre.find(params[:id])
  @genre.destroy
  redirect_to album_path(@album)
end

private
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @albums = Album.all
    render :index
  end

  def new
    @album = Album.find(params[:album_id])
    @song = @album.songs.new
    render :new
  end

  def create
    @album = Album.find(params[:album_id])
    @song = @album.songs.new(song_params)
    if @song.save
      redirect_to album_path(@album)
    else
      render :new
    end
  end

def edit
  @album = Album.find(params[:album_id])
  @song = Song.find(params[:id])
  render :edit
end

def show

  @album = Album.find(params[:album_id])
  @song = Song.find(params[:id])
  render :show
end

def update
  @song = Song.find(params[:id])
  if @song.update(song_params)
    redirect_to album_path(@song.album)
  else
    render :edit
  end
end

def destroy
  @song = Song.find(params[:id])
  @song.destroy
  redirect_to album_path(@song.album)
end

private
    def song_params
      params.require(:song).permit(:name, :lyrics)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<h1>Edit album</h1>

<%= render "layouts/album_form" %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<% if @albums.any? %>
  <ul>
    <% @albums.each do |album| %>
      <%= link_to album.name, album_path(album) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no albums yet.</p>
<% end %>


<p><%= link_to "Create new album", new_album_path %></p>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "layouts/album_form" %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<h3><%= @album.genre %></h3>

<% if @album.artists.any? %>
  <h4>Here are the artists for this album</h4>

  <% @album.artists.each do |artist| %>
  <ul>
    <li>
      <%= link_to artist.name, album_artist_path(@album, artist) %>
    </li>
  </ul>
  <% end %>
<% else %>
  <p>No artists are listed for this album... yet...</p>
<% end %>

<% if @album.songs.any? %>
  <h4>Here are the songs for this album:</h4>

  <% @album.songs.each do |song| %>
    <ul>
      <li>
        <%= link_to song.name, album_song_path(@album, song) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No songs are listed for this album.</p>
<% end %>

<p><%= link_to "Add a song", new_album_song_path(@album) %></p>
<p><%= link_to "Add a artist", new_album_artist_path(@album) %></p>

<p><%= link_to "Edit", edit_album_path(@album) %></p>
<p><%= link_to "Delete album", album_path(@album),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to albums", albums_path %></p>

app/views/artists/edit.html.erb
<h1><%= @album.name %></h1>
<h2>Edit Artists</h2>

<%= form_for [@album, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/artists/new.html.erb
<h1> <%= @album.name %> </h1>
<h2> New artist </h2>
<%= form_for [@album, @artist] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1>Artist: <%= @artist.name %></h1>
<p><%= link_to "Add a genre", new_artist_genre_path(@artist) %></p>
<p><%= link_to "Edit artist", edit_album_artist_path(@album, @artist) %></p>
<p><%= link_to "Delete artist", album_artist_path(@album, @artist),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to album", album_path(@album) %></p>

app/views/genres/edit.html.erb
<h1>Edit genre:</h1>

<%= form_for [@artist, @genre] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/genres/new.html.erb
<h1>Add a new genre:</h1>

<%= form_for [@artist, @genre] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/genres/show.html.erb
<h1>Artist: <%= @artist.name %></h1>
<% if @artist.genres.any? %>
  <h4>Here are the genres for this artist</h4>

  <% @artist.genres.each do |genre| %>
  <ul>
    <li>
      <%= link_to genre.name, artist_genre_path(@artist, genre) %>
    </li>
  </ul>
  <% end %>
<% else %>
  <p>No genres are listed for this artist... yet...</p>
<% end %>

<p><%= link_to "Add a genre", new_artist_genre_path(@artist) %></p>


<p><%= link_to "Return to albums", albums_path %></p>

app/views/layouts/_album_form.html.erb
<%= render "layouts/errors", :object => @album %>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecordStoreRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Edit song:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/new.html.erb
<h1>Add a new song:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/show.html.erb
<h1>Song: <%= @song.name %></h1>
<h2>Album: <%= @album.name %></h2>
<h3><%= @song.lyrics %></h3>

<p><%= link_to "Edit song", edit_album_song_path(@album, @song) %></p>
<p><%= link_to "Delete song", album_song_path(@album, @song),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to album", album_path(@album) %></p>